### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 're/train.txt'

### ISSUE THREAD

**Issue by whoisraibolt** [qizhen816/Tensorflow-with-own-data#1]
I unzipped the re.zip folder, however when I run the Makedata.py code I get the following error:

     reading

     Traceback (most recent call last):

         File "Makedata.py", line 69, in <module>

             O1 = Obj1.date_process()

         File "Makedata.py", line 21, in date_process

             with open(self.in1) as f:  # 读取txt里面的文件名 read train.txt

     IOError: [Errno 2] No such file or directory: 're/train.txt'

**Comment by qizhen816** [comment]
sorry I for the delay, have you tried replaced the path with absolute path ?

**Comment by whoisraibolt** [comment]
For some reason it was my Python problem, but I've fixed the problem!
